### ISSUE TITLE
Replace example data with open-source data

### ISSUE THREAD

**Issue by tom-andersson** [tom-andersson/deepsensor_gallery#2]
Currently, many of the example notebooks in `demonstrators/` use data from my local environment and are not reproducible. It would be good to replace this data with open-source data, such as this gridded US air temperature reanalysis dataset available through one line of `xarray`:
```
ds_raw = xr.tutorial.open_dataset("air_temperature")
```
Given the simplicity of the above, I suggest we aim to keep US air temperature as our key demo variable. We need open-source and easily-accessible station CSV data and auxiliary NetCDF/GeoTIFF fields like elevation & a land mask.
* @magnusross has made some progress on simplifying the acquisition of station data - are US temperature stations available through the tool you've been working with?
* I've found accessing elevation data is often not as trivial as you'd think, so this needs to be looked into.

There's a risk that the xarray `"air_temperature"` reanalysis dataset is too short to train good models with it (it only spans 2 years). However, I think the trained model predictions will look reasonable for demo purposes and we wouldn't want to be training on much larger datasets anyway.

cc @acocac

**Comment by magnusross** [comment]
Hey Tom, yes the US stations are available using the [get-station-data package](https://github.com/scotthosking/get-station-data), you can also access other stations in the GHCN around the globe. The data is daily resolution, with a bunch of different variables (max temp, precipitation etc). There is also an elevation number along with each station. 

I'm not sure how we can get easy access to more ERA5 data, I did a quick search for some packages to access but there doesn't seem to be anything that is super easy to use out there.

When I add the new notebook, it will use the get-station-data package, then maybe we can also use it for some of the existing demos.

**Comment by acocac** [comment]
@magnusross we could try to access some cloud-optimized ERA5 archives in ZARR-format from the following cloud storage sources:
- Google, https://console.cloud.google.com/marketplace/product/bigquery-public-data/arco-era5
- Amazon, https://registry.opendata.aws/ecmwf-era5/
- Microsoft, https://planetarycomputer.microsoft.com/dataset/era5-pds

There's a comprehensive explanation of the ZARR format in this e-book, https://developmentseed.org/cloud-optimized-geospatial-formats-guide/zarr/intro.html

**Comment by tom-andersson** [comment]
Hey @acocac, the above ERA5 `zarr` cloud sources look like a convenient way of grabbing reanalysis data for demonstrating DeepSensor. This could complement the station data downloader that @magnusross is working on.

I did some quick digging into the Google, Amazon, and Microsoft options. From what I could see, the Amazon and Microsoft options have a fair bit of boilerplate code, whereas the Google option is a simple one-liner.

After `pip install`ing `zarr` and `gcsfs` we can do this:
```
import xarray as xr
import time
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cf

era5 = xr.open_zarr(
    "gs://gcp-public-data-arco-era5/ar/1959-2022-full_37-1h-0p25deg-chunk-1.zarr-v2",
    consolidated=True,
)

# Select 2020 for surface temperature
da = era5['2m_temperature'].sel(time=slice('2020-01-01', '2020-12-31')) # Could also slice lat/lon here
tic = time.time()
da = da.load()
print(f"{da.nbytes / 1e9:.2f} GB of ERA5 loaded in {time.time() - tic:.2f} s")

# Plot first date
fig, ax = plt.subplots(1, 1, figsize=(7, 7), subplot_kw=dict(projection=ccrs.PlateCarree()))
(da.isel(time=0) - 273.15).plot(ax=ax, add_colorbar=False)
ax.coastlines()
ax.add_feature(cf.BORDERS)
```
![output](https://github.com/tom-andersson/deepsensor_gallery/assets/26459412/d7e39483-471b-41d2-b306-45f6d187274e)

On the HPC I use, it took ~3 minutes to download 1 year of hourly global surface temperature data (8784 time slices & 35 GB). Downloading 1 month took 20 seconds, and further slicing spatially to Germany took this to 17 seconds (which is not a big speedup from the global download, presumably due to the way the data is stored).

This feels workable to have within demonstrators. We could use a conservative date range by default, e.g. 2 months, and allow the user to specify a longer temporal window if they want to scale up and get better results by downloading more data.

**Comment by patel-zeel** [comment]
Hi @tom-andersson and @acocac,

The Google option looks the most convenient one-liner! As an additional option, [WeatherBench](https://github.com/pangeo-data/WeatherBench) has a set of [coarse resolution datasets](https://mediatum.ub.tum.de/1524895) (5.625deg, 2.8125deg, ...). For example, `2m_temperature` is hourly data of size 2.2G for 5.625deg and 8.5G for 2.8125deg from 1979 to 2018. The [Climate-Learn](https://github.com/aditya-grover/climate-learn) library has [a method](https://github.com/aditya-grover/climate-learn/blob/b48fb0242acc47e365af86bfbd9dd86e9dcbd6d2/src/climate_learn/data/download.py#L59) to download it and a bunch of other datasets.

**Comment by tom-andersson** [comment]
It would be convenient if we could access daily-average ERA5 data through Google Cloud; have raised an issue about this here https://github.com/google-research/arco-era5/issues/61

**Comment by tom-andersson** [comment]
We now have a `deepsensor.data.sources` module that provides a suite of functions for downloading station data, ERA5 data, and auxiliary data directly into pandas/xarray. See the DeepSensor documentation for examples: https://tom-andersson.github.io/deepsensor/getting-started/data_requirements.html

Big thanks to @magnusross for improving the `get-station-data` repository (which is now a DeepSensor dependency)!
